// test variable for 1 bar of music
const soundsToPlay = [false, true, false, false, false, true];

// result generated by the user when he clicks on the pads on the screen (all false at the start)
let partitionUser = [
    [false, false, false, false, false, false],
    [false, false, false, false, false, false],
    [false, false, false, false, false, false],
    [false, false, false, false, false, false]
];


// partitions to be played by the computer - hardcoded
const partitionsToPickFrom = [{
        name: '"Just The Kick"',
        tempo: 120,
        difficulty: 1,
        notes: [
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [false, false, false, false, false, false],
            [false, false, false, false, false, false]
        ]
    },
    {
        name: '"Many Sounds"',
        tempo: 120,
        difficulty: 2,
        notes: [
            [true, false, false, false, false, true],
            [false, true, false, false, false, false],
            [false, false, false, true, false, false],
            [false, false, false, false, true, false]
        ]
    },
    {
        name: '"Getting Started"',
        tempo: 120,
        difficulty: 2,
        notes: [
            [true, false, false, false, false, false],
            [false, false, true, false, false, false],
            [true, false, false, false, false, false],
            [false, false, true, false, false, true]
        ]
    },
    {
        name: '"Rock You!"',
        tempo: 60,
        difficulty: 4,
        notes: [
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [false, false, false, false, false, true],
            [false, false, false, false, false, false]
        ]
    },
    {
        name: '"Funky"',
        tempo: 150,
        difficulty: 4,
        notes: [
            [true, false, true, false, false, false],
            [false, false, true, false, false, false],
            [true, false, true, false, false, false],
            [false, false, true, false, false, true]
        ]
    },
    {
        name: '"Here We Go"',
        tempo: 130,
        difficulty: 5,
        notes: [
            [true, false, true, false, true, true],
            [false, false, true, false, false, false],
            [true, true, true, false, false, false],
            [false, false, true, true, true, false]
        ]
    },
    {
        name: '"Hardcore Beat"',
        tempo: 220,
        difficulty: 4.5,
        notes: [
            [true, false, false, false, true, false],
            [true, false, false, false, true, false],
            [true, false, true, false, false, false],
            [true, false, false, true, true, false]
        ]
    }
]

const extraPartitions = [{
    name: '"Random Stuff"',
    tempo: 92,
    difficulty: 3.5,
    notes: [
        [true, false, true, false, true, false],
        [false, true, false, true, false, true],
        [false, false, true, false, false, true],
        [false, true, true, false, false, false]
    ]
}]