// test variable for 1 bar of music
const soundsToPlay = [false, true, false, false, false, true];

// result generated by the user when he clicks on the pads on the screen (all false at the start)
const partitionUser = [
    [false, false, false, false, false, false],
    [false, false, false, false, false, false],
    [false, false, false, false, false, false],
    [false, false, false, false, false, false]
];


// partitions to be played by the computer - hardcoded
const timeoutTempoDJ = 60000 / (partitionsToPickFrom[0].tempo * 2);
const partitionDJ = partitionsToPickFrom[0].notes;


const partitionsToPickFrom = [{
        name: 'First Beat',
        tempo: 120,
        difficulty: 2,
        notes: [
            [true, false, false, false, false, false],
            [false, false, false, false, false, false],
            [true, false, false, false, false, false],
            [false, false, true, true, false, false]
        ]
    },
    {
        name: 'Second Beat',
        tempo: 150,
        difficulty: 4,
        notes: [
            [true, false, false, false, true, false],
            [false, false, false, false, false, false],
            [true, true, false, false, false, false],
            [false, false, true, true, false, false]
        ]
    }
]