// test variable for 1 bar of music
const soundsToPlay = [false, true, false, false, false, true];

// result generated by the user when he clicks on the pads on the screen (all false at the start)
let partitionUser = [
    [false, false, false, false, false, false],
    [false, false, false, false, false, false],
    [false, false, false, false, false, false],
    [false, false, false, false, false, false]
];


// partitions to be played by the computer - hardcoded
const easyPartitions = [{
        name: '"Just The Kick"',
        tempo: 120,
        difficulty: 1,
        time: 45,
        notes: [
            [true, false, false, false, false, false],
            [false, false, false, false, false, false],
            [true, false, false, false, false, false],
            [false, false, false, false, false, false]
        ]
    },
    {
        name: '"Drop The Bass"',
        tempo: 120,
        difficulty: 2,
        time: 45,
        notes: [
            [false, false, false, false, false, true],
            [false, false, false, false, false, true],
            [false, false, false, true, false, false],
            [false, true, false, false, false, false]
        ]
    },
    {
        name: '"Rock You!"',
        tempo: 60,
        time: 45,
        difficulty: 4,
        notes: [
            [true, false, false, false, false, false],
            [true, false, false, false, false, false],
            [false, true, false, false, true, false],
            [false, false, false, false, false, false]
        ]
    },
    {
        name: '"Funky"',
        tempo: 150,
        time: 60,
        difficulty: 4,
        notes: [
            [true, false, true, false, false, true],
            [false, false, true, false, false, false],
            [true, false, true, false, true, false],
            [false, false, true, false, true, true]
        ]
    }

]


const hardPartitions = [{
        name: '"Getting Started"',
        tempo: 120,
        difficulty: 2,
        time: 60,
        notes: [
            [true, false, false, false, false, false],
            [false, false, true, false, false, false],
            [true, false, false, false, false, true],
            [false, false, true, false, false, true]
        ]
    },
    {
        name: '"Here We Go"',
        tempo: 130,
        time: 90,
        difficulty: 5,
        notes: [
            [true, false, true, false, true, true],
            [false, false, true, false, false, false],
            [true, true, true, false, false, false],
            [false, false, true, true, true, false]
        ]
    },
    {
        name: '"Hardcore Beat"',
        tempo: 220,
        time: 90,
        difficulty: 7,
        notes: [
            [true, false, false, false, true, false],
            [true, false, false, false, true, false],
            [true, false, true, false, false, false],
            [true, false, false, true, true, false]
        ]
    },
    {
        name: '"Random Stuff"',
        tempo: 92,
        difficulty: 7,
        time: 90,
        notes: [
            [true, false, true, false, true, false],
            [false, true, false, true, false, true],
            [false, false, true, false, false, true],
            [false, true, true, false, false, false]
        ]
    }
]